#+TITLE: Deploy scQTL browser
#+AUTHOR: Abhishek Sarkar
#+PROPERTY: header-args:sh :eval never-export :results output

* Test environment

  Get a local compute node.

  #+BEGIN_SRC sh :session midway2
    srun -n1 --partition=broadwl --pty bash
    cd /project2/mstephens/aksarkar/projects/singlecell-qtl/browser/
    source activate scqtl
  #+END_SRC

  #+RESULTS:
  : 
  : cd /project2/mstephens/aksarkar/projects/singlecell-qtl/browser/
  : cd /project2/mstephens/aksarkar/projects/singl ecell-qtl/browser/
  : source activate scqtl

  (Re)start the browser

  #+BEGIN_SRC sh :session midway2
    pkill -u aksarkar bokeh
    bokeh serve fano-qtls simulation poisson-beta --address $(hostname -i) --allow-websocket-origin=$(hostname -i):5006 &
    echo "http://$(hostname -i):5006"
  #+END_SRC

  #+RESULTS:
  : pkill -u aksarkar bokeh
  : bokeh serve fano-qtls simulation poiss on-beta --address $(hostname -i) --allow-websocket-origin=$(hostname -i):5006 &
  : [1] 32569
  : echo "http://$(hostname -i):5006"
  : echo 'org_babel_sh_eoe'
  : http://10.50.221.17:5006

* Production environment

  Start a remote session on ~shiny.stephenslab.uchicago.edu~.

  #+BEGIN_SRC sh :session shiny
  ssh shiny
  #+END_SRC

  #+RESULTS:
  |         |                |                          |          |          |            |                  |         |                 |
  | Welcome | to             | Ubuntu                   | 16.04    | LTS      | (GNU/Linux | 4.4.0-98-generic | x86_64) |                 |
  |         |                |                          |          |          |            |                  |         |                 |
  | *       | Documentation: | https://help.ubuntu.com/ |          |          |            |                  |         |                 |
  |         |                |                          |          |          |            |                  |         |                 |
  | 231     | packages       | can                      | be       | updated. |            |                  |         |                 |
  | 23      | updates        | are                      | security | updates. |            |                  |         |                 |
  |         |                |                          |          |          |            |                  |         |                 |
  |         |                |                          |          |          |            |                  |         |                 |
  | ***     | System         | restart                  | required | ***      |            |                  |         |                 |
  | Last    | login:         | Tue                      | Apr      | 3        |   20:33:33 |             2018 | from    | 107.210.252.224 |

  The version of ~vagrant~ on ~shiny.stephenslab.uchicago.edu~ is old, and
  appears to use a broken URL to download Vagrant boxes. Add the Debian Stretch
  box using the full URL.

  #+BEGIN_SRC sh :session shiny
  vagrant box add "https://app.vagrantup.com/debian/boxes/stretch64"
  #+END_SRC

  (Re)start the VM.

  #+BEGIN_SRC sh :session shiny :results output
  mkdir -p scqtl-browser
  cd scqtl-browser
  vagrant halt
  vagrant up --no-provision
  #+END_SRC

  #+RESULTS:
  #+begin_example

  aksarkar@shiny:~/scqtl-browser$ aksarkar@shiny:~/scqtl-browser$ [0mBringing machine 'default' up with 'virtualbox' provider...[0m
  default: Checking if box 'debian/stretch64' is up to date...[0m
  default: Clearing any previously set forwarded ports...[0m
  default: Clearing any previously set network interfaces...[0m
  default: Preparing network interfaces based on configuration...[0m
  [0m    default: Adapter 1: nat[0m
  default: Forwarding ports...[0m
  5006 (host) (adapter 1)[0m
  2222 (host) (adapter 1)[0m
  default: Running 'pre-boot' VM customizations...[0m
  default: Booting VM...[0m
  default: Waiting for machine to boot. This may take a few minutes...[0m
  [0m    default: SSH address: 127.0.0.1:2222[0m
  [0m    default: SSH username: vagrant[0m
  [0m    default: SSH auth method: private key[0m
  default: Machine booted and ready![0m
  default: Checking for guest additions in VM...[0m
  [0m    default: No guest additions were detected on the base box for this VM! Guest
      default: additions are required for forwarded ports, shared folders, host only
      default: networking, and more. If SSH fails on this machine, please install
      default: the guest additions and repackage the box to continue.
      default: 
      default: This is not an error message; everything may continue to work properly,
      default: in which case you may ignore this message.[0m
  default: Rsyncing folder: /home/aksarkar/scqtl-browser/ => /vagrant[0m
  [0;31mThere was an error when attempting to rsync a synced folder.
  Please inspect the error message below for more info.

  Host path: /home/aksarkar/scqtl-browser/
  Guest path: /vagrant
  Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=/tmp/ssh.214 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/home/aksarkar/scqtl-browser/.vagrant/machines/default/virtualbox/private_key' --exclude .vagrant/ /home/aksarkar/scqtl-browser/ vagrant@127.0.0.1:/vagrant
  Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
  deploy.org"
  rsync: write failed on "/vagrant/browser.db": No space left on device (28)
  rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]
  [0m
  #+end_example

  ssh into the VM.

  #+BEGIN_SRC sh :session shiny
  vagrant global-status
  #+END_SRC

  #+RESULTS:
  #+begin_example
  [0mid       [0m[0mname    [0m[0mprovider   [0m[0mstate   [0m[0mdirectory                           [0m[0m[0m
  [0m------------------------------------------------------------------------[0m
  [0md0744a6  [0m[0mdefault [0m[0mvirtualbox [0m[0mrunning [0m[0m/home/aksarkar/scqtl-browser        [0m[0m[0m
  [0m 
  The above shows information about all known Vagrant environments
  on this machine. This data is cached and may not be completely
  up-to-date. To interact with any of the machines, you can go to
  that directory and run Vagrant, or you can use the ID directly
  with Vagrant commands from any directory. For example:
  "vagrant destroy 1a2b3c4d"[0m
  #+end_example

  #+BEGIN_SRC sh :session shiny :results output
  vagrant ssh d0744a6
  #+END_SRC

  #+RESULTS:
  #+begin_example

  1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64

  The programs included with the Debian GNU/Linux system are free software;
  the exact distribution terms for each program are described in the
  individual files in /usr/share/doc/*/copyright.

  Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
  permitted by applicable law.
  Last login: Wed Apr  4 01:33:47 2018 from 10.0.2.2
  #+end_example

  The data are available on the VM under ~/vagrant~. Fake the location of the
  database as it appears on the test server (~*.midway2.rcc.uchicago.edu~).

  #+BEGIN_SRC sh :session shiny
  sudo mkdir -p /project2/mstephens/aksarkar/projects/singlecell-qtl/
  sudo ln -s /vagrant /project2/mstephens/aksarkar/projects/singlecell-qtl/browser
  #+END_SRC

  Install ~miniconda3~ as user ~vagrant~.

  #+BEGIN_SRC sh :session shiny
  wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  bash Miniconda3-latest-Linux-x86_64.sh -p
  echo "export PATH=$PATH:$HOME/miniconda3/bin" >>$HOME/.bashrc
  . $HOME/.bashrc
  #+END_SRC

  Initialize a new environment. We don't need the full environment from
  ~singlecell-qtl~.

  #+BEGIN_SRC sh :session shiny
  conda env create -n "scqtl-browser" numpy scipy pandas matplotlib bokeh
  #+END_SRC

  ~rsync~ the code and data to the server.

  #+BEGIN_SRC sh :dir /scratch/midway2/aksarkar/singlecell
  sbatch --partition=broadwl
  #!/bin/bash
  rsync -au /project2/mstephens/aksarkar/projects/singlecell-qtl/browser/ shiny:scqtl-browser/
  #+END_SRC

  #+RESULTS:
  : Submitted batch job 44985280

  Start the QTL browser. The code/data are available under ~/vagrant~ inside the VM.

  #+BEGIN_SRC sh :session shiny
  cd /vagrant
  source activate scqtl-browser
  nohup bokeh serve simulation fano-qtls --port 5006 --allow-websocket-origin=shiny.stephenslab.uchicago.edu:5006 &
  #+END_SRC

  #+RESULTS:
  : 
  : (scqtl-browser) vagrant@stretch:/vagrant$ [1] 618
