---
title: "Analysis"
output:
  workflowr::wflow_html:
    toc: false
---

* [Analysis of total counts from processing pipeline](totals.html)
* [Descriptive statistics](descriptive-stats.html)
* [Diminishing returns of sequencing depth](dim-returns.html)
* [Exploratory analysis with PCA](pca.html)
* [Correlation of covariates with PCs of highly variable genes](pca-variable.html)
* [ERCC capture efficiency](ercc.html)
* [Identifying single cells](identity.html)
* [Pairwise correlations](correlations.html)
* [Paritioning variance across different factors](partition.html)
* [Sample quality control](sampleqc.html)
* [Filter genes](filter-gene.html)
* [Gene set and pathway overdispersion analysis](scde-all.html)
* [Dimensionality reduction](dim-reduction.html)
* [Identification of noisy genes](noisygene.html)
* [UMI count distribution stratified by genotype](sc-stratified-geno.html)
* [Single cell/bulk RNA-Seq concordance](sc-vs-bulk.html)
* [Power to detect QTLs in single cell data](power.html)
* [Mean/dispersion estimation](zinb.html)
* [QTL mapping pipeline](qtl-mapping.html)
