---
title: "Data collection overview"
author: "John Blischak"
date: 2017-10-25
output:
  html_document:
    toc: false
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
knitr::opts_chunk$set(echo = FALSE)
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r analysis, message=FALSE}
library("dplyr")
library("DT")
library("Biobase")
source("../code/functions.R")
fname <- Sys.glob("../data/eset/*.rds")
eset <- Reduce(combine, Map(readRDS, fname))
eset_quality <- eset[, eset$cell_number == 1 & eset$tra1.60 & eset$valid_id]
eset_hs <- eset_quality[fData(eset_quality)$source == "H. sapiens", ]
eset_hs_clean <- eset_hs[rowSums(exprs(eset_hs)) != 0, ]
eset_hs_clean <- eset_hs_clean[apply(exprs(eset_hs_clean), 1, present), ]
sums <- colSums(exprs(eset_hs_clean))
collection <- pData(eset_hs_clean) %>%
  select(chip_id, detect_hs) %>%
  cbind(sums) %>%
  group_by(chip_id) %>%
  summarize(n = n(),
            detect_med = median(detect_hs),
            sum_med = median(sums)) %>%
  arrange(desc(n))
```

We have collected a total of `r ncol(eset_hs_clean)` cells\* for a total of
`r length(unique(eset_hs_clean$chip_id))` individuals.

\* This is a high estimate because only a few QC filters were used. The
number will decrease when more stringent QC filters are applied.

```{r datatable}
datatable(collection, options = list(pageLength = nrow(collection)),
          colnames = c("Individual", "Number of cells",
                       "Median number of genes detected",
                       "Median number of molecules"))
```
