---
title: "License"
output:
  html_document:
    toc: false
---

The code is available under the [MIT license][mit]. The text, data, and figures
are available under the [CC-BY license][cc-by]. Please see the file
[LICENSE][license] for the full license text.

Both of these allow you to reuse, adapt, or redistribute the content as long as
you attribute us. If you use our data, please attribute us as follows:

> The single-cell RNA-seq data was generated by the Gilad lab at the University
> of Chicago and the Pritchard lab at Stanford University (see
> https://github.com/jdblischak/singlecell-qtl for details).

If you use our code, please attribute us as follows:

> The code used to process the single-cell RNA-seq data was adapted from the
> code written by the Gilad lab at the University of Chicago and the Pritchard
> lab at Stanford University (see https://github.com/jdblischak/singlecell-qtl
> for details).

For academic publications, please cite our published paper:

> Sarkar AK, Tung PY, Blischak JD, Burnett JE, Li YI, et al. (2019) Discovery
> and characterization of variance QTLs in human induced pluripotent stem cells.
> PLOS Genetics 15(4): e1008045. https://doi.org/10.1371/journal.pgen.1008045

You can find a BibTeX entry for the above citation in [CITATION][citation].

[cc-by]: https://creativecommons.org/licenses/by/4.0/
[citation]: https://github.com/jdblischak/singlecell-qtl/blob/master/CITATION
[license]: https://github.com/jdblischak/singlecell-qtl/blob/master/LICENSE
[mit]: https://choosealicense.com/licenses/mit/
